### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by ghost** [DhavalKapil/libdheap#1]
$ LD_PRELOAD=./libdheap.so LIBDHEAP_DEBUG=1 /bin/ls 
[LIBDHEAP DEBUG] : malloc(5)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2568018 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2568068 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x25690b8 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256a108 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256b158 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256c1a8 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256d1f8 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256e248 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x256f298 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x25702e8 0x7fe63edf7230
[...]
LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2f59cb8 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2f5ad08 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2f5bd58 0x7fe63edf7230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x2f5cda8 0x7fe63edf7230
Segmentation fault (core dumped)

$ LD_PRELOAD=./libdheap.so LIBDHEAP_DEBUG=1 ./buffer_overflow 
[LIBDHEAP DEBUG] : malloc(10)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1382018 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1382078 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x13830c8 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1384118 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1385168 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x13861b8 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1387208 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x1388258 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x13892a8 0x7f3e85ded230
[LIBDHEAP DEBUG] : malloc(4096)
[LIBDHEAP DEBUG] : Allocating chunk: 0x138a2f8 0x7f3e85ded230
[..]
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b2b38 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b2f88 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b33d8 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b3828 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b3c78 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b40c8 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b4518 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b4968 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b4db8 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b5208 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b5658 0x7f33b0681230
[LIBDHEAP DEBUG] : malloc(1024)
[LIBDHEAP DEBUG] : Allocating chunk: 0x12b5aa8 0x7f33b0681230
[LIBDHEAP DEBUG] : Segmentation fault (core dumped)

$ uname -a
Linux xps 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 12:47:52 CEST 2017 x86_64 GNU/Linux
$ /lib/libc.so.6 
GNU C Library (GNU libc) stable release version 2.25, by Roland McGrath et al.

**Comment by DhavalKapil** [comment]
Seems like a problem on Arch, can you compare your issue once with #3 ?

**Comment by DhavalKapil** [comment]
In that case, could you once run ls under gdb?

```sh
gdb /bin/ls

> set environment LD_PRELOAD=....
> run
```

Let me know the output. Thanks!

**Comment by ghost** [comment]
it works now with the last commit, no segfaults also with the tests in the code.
